import { supabase } from './client';
import { AcademicRequest, PriorityLevel, RequestStatus } from '../../types';

/**
 * Row returned by the Request table, including the joined Student's name.
 * We select `Student(Student_Name)` so the request row carries the real name.
 */
interface RequestViewRow {
  id: string;
  created_at: string;
  Request_ID: string | number;
  Request_Type: string;
  Request_Date: string;
  Submission_Time: string;
  Description: string | null;
  Current_Status: string | null;
  Student_ID: string | null;
  Student?: { Student_Name: string | null } | null;
}

function rowToRequest(row: RequestViewRow): AcademicRequest {
  return {
    id: String(row.Request_ID),
    studentName: row.Student?.Student_Name ?? 'Unknown',
    studentId: row.Student_ID ?? '',
    type: row.Request_Type,
    courseCode: '',
    courseName: '',
    department: '',
    priority: 'Medium' as PriorityLevel,
    submittedDate: row.Request_Date,
    processedDate: undefined,
    status: (row.Current_Status ?? 'In Progress') as RequestStatus,
    notes: row.Description ?? undefined,
    reason: row.Description ?? undefined,
  };
}

/**
 * Fetch requests with the student's name joined in.
 * The FK is Request.Student_ID -> Student.Student_ID.
 */
const REQUEST_SELECT = '*, Student(Student_Name)';

export async function listActiveRequests(): Promise<AcademicRequest[]> {
  const { data, error } = await supabase
    .from('Request')
    .select(REQUEST_SELECT)
    .order('Request_Date', { ascending: false });

  if (error) {
    console.error('Error loading active requests:', error);
    throw error;
  }

  return ((data ?? []) as RequestViewRow[]).map(rowToRequest);
}

export async function listStudentRequests(
  studentId: string,
): Promise<AcademicRequest[]> {
  const { data, error } = await supabase
    .from('Request')
    .select(REQUEST_SELECT)
    .eq('Student_ID', studentId)
    .order('Request_Date', { ascending: false });

  if (error) {
    console.error('Error loading student requests:', error);
    throw error;
  }

  return ((data ?? []) as RequestViewRow[]).map(rowToRequest);
}

export async function listRequestHistory(): Promise<AcademicRequest[]> {
  const { data, error } = await supabase
    .from('Request')
    .select(REQUEST_SELECT)
    .order('Request_Date', { ascending: false });

  if (error) {
    console.error('Error loading request history:', error);
    throw error;
  }

  return ((data ?? []) as RequestViewRow[]).map(rowToRequest);
}

export interface NewRaiseCapacityRequest {
  studentId: string;
  courseId: number;
  sectionId: number;
  term: string;
  reason: string;
  submittedDate: string;
}

/**
 * Create a Raise Capacity request.
 *
 * The Request_ID is generated by the DB trigger `trg_generate_request_id`
 * (BEFORE INSERT on Request). We deliberately do NOT send a Request_ID —
 * the trigger overwrites anything we send. Instead we `.select('Request_ID')`
 * after the insert to read back what the trigger generated, and reuse it
 * for the Raise_Capacity row so the FK points at a real Request.
 *
 * The Term is passed by the caller (from the real Section row), since
 * Raise_Capacity.Term is NOT NULL.
 */
export async function createRaiseCapacityRequest(
  req: NewRaiseCapacityRequest,
): Promise<string> {
  const { data, error: requestError } = await supabase
    .from('Request')
    .insert({
      Request_Type: 'Raise Capacity',
      Request_Date: req.submittedDate,
      Submission_Time: new Date().toISOString().slice(11, 19),
      Description: req.reason,
      Current_Status: 'In Progress',
      Student_ID: req.studentId,
    })
    .select('Request_ID')
    .single();

  if (requestError || !data) {
    console.error('Error creating Request:', requestError);
    throw requestError ?? new Error('Request insert returned no row');
  }

  const generatedRequestId = (data as { Request_ID: string }).Request_ID;

  const { error: subtypeError } = await supabase.from('Raise_Capacity').insert({
    Request_ID: generatedRequestId,
    Reason: req.reason,
    Course_ID: req.courseId,
    Section_ID: req.sectionId,
    Term: req.term,
  });

  if (subtypeError) {
    console.error('Error creating Raise_Capacity:', subtypeError);
    await supabase.from('Request').delete().eq('Request_ID', generatedRequestId);
    throw subtypeError;
  }

  return generatedRequestId;
}

export async function listRaiseCapacityRequests() {
  const { data, error } = await supabase
    .from('Request')
    .select(REQUEST_SELECT)
    .eq('Request_Type', 'Raise Capacity')
    .order('Request_Date', { ascending: false });

  if (error) {
    console.error('Error loading raise capacity requests:', error);
    throw error;
  }

  return data ?? [];
}

/**
 * Load all sections for the most recent term, with their parent Course attached.
 *
 * Two queries (not a Supabase auto-join) so we don't depend on how many FK
 * relationships exist between Section and Course.
 *
 * Section_ID is NOT unique on its own — it repeats across courses and terms
 * (each course has e.g. its own "section 61"). So we filter to the latest
 * term to get exactly one row per course.
 */
export async function listCourseSections() {
  // 1. Find the most recent term in Section.
  const { data: termRow, error: termError } = await supabase
    .from('Section')
    .select('Term')
    .order('Term', { ascending: false })
    .limit(1)
    .maybeSingle();

  if (termError) {
    console.error('Error loading latest term:', termError);
    throw termError;
  }

  const currentTerm = termRow?.Term;

  // 2. Fetch sections for that term only.
  let sectionQuery = supabase
    .from('Section')
    .select('Section_ID, Term, Current_Capacity, Total_Capacity, Additional_Capacity, Course_ID')
    .order('Course_ID', { ascending: true });

  if (currentTerm !== undefined && currentTerm !== null) {
    sectionQuery = sectionQuery.eq('Term', currentTerm);
  }

  const { data: sections, error: sectionError } = await sectionQuery;

  if (sectionError) {
    console.error('Error loading sections:', sectionError);
    throw sectionError;
  }

  if (!sections || sections.length === 0) return [];

  // 3. Fetch the courses referenced by those sections.
  const courseIds = [...new Set(sections.map((s) => s.Course_ID))];

  const { data: courses, error: courseError } = await supabase
    .from('Course')
    .select('Course_ID, Course_Name, Credit_Hours')
    .in('Course_ID', courseIds);

  if (courseError) {
    console.error('Error loading courses:', courseError);
    throw courseError;
  }

  const courseById = new Map((courses ?? []).map((c) => [c.Course_ID, c]));

  // 4. Attach each Course to its Section.
  return sections.map((s) => ({
    ...s,
    Course: courseById.get(s.Course_ID) ?? null,
  }));
}